name: "Unity export"
on: 
  push: 
    branches: 
      - main

env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: \"CarryOn\"

jobs:
  deploy-web:
    name: Web Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache
        uses: actions/cache@v2
        with:
          path: UnityProject/Library
          key: Library-MarioStranding-WebGL
          restore-keys: |
            Library-MarioStranding-
            Library-

      - name: Web Build
        uses: game-ci/unity-builder@v2
        working-directory: UnityProject
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        #   UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        #   UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        working-directory: UnityProject
        with:
          name: web
          path: ./build/WebGL/

    #   - name: Itch.io
    #     env: 
    #       BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
    #     run: butler push ./build/web ${{ secrets.ITCHIO_USERNAME }}/${{ secrets.ITCHIO_GAME }}:web
